reservation/urls.py
from reservation import views
from django.urls import path
from django.contrib import admin




urlpatterns = [
    path('', views.home, name='home'),# The '' - need to match -> HTML. After , is the view name you want to link it to. Name parameter has no function as of now. 
    path('home', views.home, name='home'),
    path('menu', views.dishList.as_view(), name='menu'),
    path('make_dish', views.MakeDish.as_view(), name='make_dish'),
    path('reserv_table', views.reserv_table, name='reserv_table'),
    path('bookings_navigation', views.bookings_navigation, name='bookings_navigation'),
    path('delete/<reserv_id>', views.delete_reservation, name='delete'),
    path('delete_dish/<dish_id>', views.DeleteDish.as_view(), name='delete_dish'),
]

# Gotcha, okay so the home template will need to be rendered in one of the views. Conventionally, you can call this home if you want. So you would have:
#def home():
#    return render(request, reservation/home.html)
#Then, in your urls.py you would have:
#path('', views.home, name='home'),

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from reservation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reservation.urls"), name="reservation.url"),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

reservation/models.py
from django.db import models
from datetime import datetime
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User

# Create your models here.


class reservation(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(default='Your email here.')
    phone = models.BigIntegerField(default='0', blank=True)
    persons = models.BigIntegerField(default='0', blank=True) 
    date = models.DateTimeField(default=datetime.now, blank=True) 

    def __str__(self):
        return self.name
        

class dish(models.Model):
    name = models.CharField(max_length=255)
    text = models.CharField(max_length=5000)
    featured_image = CloudinaryField("image", default='palceholder')
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

reservation/forms.py
from .models import dish
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class dishForm(forms.ModelForm):
    text = forms.CharField(widget=SummernoteWidget())
    
    class Meta:
        model = dish
        fields = ['name', 'text', 'featured_image']
       

reservation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from .models import reservation, dish
from .forms import dishForm
import datetime



def home(self):
    return render(self, 'home.html')


#def menu(self):
 #   menuItem = dish.objects.all()
 #   context = {
 #       'menuItem' : menuItem
 #   }
 #   return render(self, 'reservation/menu.html',context)


 #Bookings Code


def bookings_navigation(self):
    person = reservation.objects.all()
    context = {
        'person' : person
    }
    return render(self, 'bookings.html', context)


def reserv_table(request):
    person = reservation.objects.all()
    context = {
        'person' : person
    }
    if request.method == 'POST':
        name = request.POST.get('reservation_name')
        email = request.POST.get('email_name')
        phone = request.POST.get('number_name')
        persons = request.POST.get('number_persons')
        date = request.POST.get('date_time')
        reservation.objects.create(name=name, email=email, phone=phone, persons=persons, date=date)
    return render(request, 'reservation.html', context)


def delete_reservation(request, reserv_id):
    reserv = get_object_or_404(reservation, id=reserv_id)
    reserv.delete()

    return redirect('bookings_navigation')


#Dish Code


class dishList(generic.ListView):
    model = dish
    queryset = dish.objects.all()
    template_name = 'menu.html'


class MakeDish(generic.CreateView):
    model = dish
    form_class = dishForm
    template_name = 'dishmaker.html'
    success_url = 'menu'
    success_mesage = 'New dish added!'

    def get_context_data(self, **kwargs):
        context = super(MakeDish, self).get_context_data(**kwargs)
        context['photos'] = dish.objects.all().order_by('-created_on')
        return context


class DeleteDish(generic.DeleteView):
    model = dish
    template_name = 'menu.html'
    success_url = 'menu'
    success_mesage = 'Dish deleted!'
    
    def get_context_data(self, **kwargs):
        context = super(DeleteDish, self).get_context_data(**kwargs)
        return context

reservation/templates/reservation/bookings.html
{% extends "reservation/base.html" %}
  
{% block content %}

  <!-- display field -->
<h1 class="">Bookings already made.</h1>
 <div class="row" >

    <div class="col-sm-2">
    </div>

    <div class="col-sm-8">
      <div class="row" >
   {% for x in person %} 
   
    <div class="col-sm-4" id="booking_container">
      <h5> {{ x.name }} </h5>
      <h6> {{ x.email }} </h6>
      <h6> {{ x.phone }} </h6>
      <h6> {{ x.persons }} </h6>
      <h6> {{ x.date }} </h6>
      <h6>
          <a href = "/delete/{{ x.id }} " method="POST">
              <button>Delete</button>
          </a>
      </p>
    </div>
    
   {% endfor %} 
    </div>
  </div>

   <div class="col-sm-2">
   </div>


</div>
{% endblock %}

reservation/templates/reservation/dishmaker.html
{% extends "reservation/base.html" %}
  
{% block content %}

<form action="{% url 'make_dish' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


<!-- Original form to make a dish. 
<div class="container-fluid" id="bgimg">
    <div class="container mt-3" id="input">
        <h2 class="text-center text-light">Make your own dish!</h2>
        
        <form class="container mt-3" method="POST" action="make_dish">
            {% csrf_token %}
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="id_name" placeholder="Name" name="dish_name" maxlength="50">
                    <label for="id_name">Name</label>
                </div>
                <div class="form-floating mb-3 mt-3">
                    
                    <label for="text">Dish Description</label>
                    {{ foobar|safe }}
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
</div>
-->

<!-- New attept using a form class.-->
{% endblock %}

reservation/templates/reservation/home.html
{% extends "reservation/base.html" %}
  
{% block content %}
<h1>Tasty eats!</h1>
<h2>Here at tasty eats house!</h2>
{% endblock %}

reservation/templates/reservation/menu.html
{% extends "reservation/base.html" %}
  
{% block content %}


<h1 class="">Menu.</h1>
 <div class="row" >

    <div class="col-sm-2">
    </div>

    <div class="col-sm-8">
      <div class="row" >
   {% for dish in dish_list %} 
   
    <div class="col-sm-4" id="booking_container">

      <h5> {{ dish.name|safe }} </h5>
      <h5> {{ dish.text|safe }} </h5>

      <!--{% if "placeholder" in post.featured_image.url %}
          <img class="card-img-top"
            src="https://www.google.at/url?sa=i&url=https%3A%2F%2Fwww.medienwerkstatt-online.de%2Flws_wissen%2Fvorlagen%2Fshowcard.php%3Fid%3D17480%26edit%3D0&psig=AOvVaw1v5FIxfYll-Q7tQXrPpB93&ust=1687443114858000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIjs1M3F1P8CFQAAAAAdAAAAABAE">
       {% else %}-->
      

            <img class="card-img-top" src=" {{ dish.featured_image.url }}" alt="Tasty dish Image!">

        <!--{% endif %}-->
       
      
    </div>
    
   {% endfor %} 
    </div>
  </div>

   <div class="col-sm-2">
   </div>


</div>
{% endblock %}

reservation/templates/reservation/reservation.html
{% extends "reservation/base.html" %}

{% block content %}


    <!-- imput field -->
<div class="container-fluid" id="bgimg">
    <div class="container mt-3" id="input">
        <h2 class="text-center text-light">Book a table!</h2>
        
        <form class="container mt-3" method="POST" action="reserv_table">
            {% csrf_token %}
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="id_name" placeholder="Enter email" name="reservation_name" maxlength="50">
                    <label for="id_name">Name</label>
                </div>
                <div class="form-floating mb-3 mt-3">
                    <input type="email" class="form-control" id="id_email" placeholder="Enter email" name="email_name" maxlength="50">
                    <label for="email">Email</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="number" class="form-control" id="id_number" placeholder="Phone number?" name="number_name" maxlength="12">
                    <label for="id_number">Phone number</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="number" class="form-control" id="id_persons" placeholder="How Many?" name="number_persons"maxlength="2">
                    <label for="id_persons">Number of People</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="datetime-local" class="form-control" id="id_date" placeholder="Date?" name="date_time">
                    <label for="id_date">Date</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
</div>
   


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </script>
    <title>Octi's Restaurant</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<!-- Navigation -->
<nav class="navbar navbar-expand-sm justify-content-center bg-dark">
    
        <ul class="navbar-nav">

            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">LogOut</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'make_dish' %}">Dish Maker 6000!</a>
            </li>
            
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">LogIn</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
            </li>

            {% endif %}
                        
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Menu</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'reserv_table' %}">Make a booking!</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'bookings_navigation' %}">View Bookings</a>
            </li>
        </ul>
    
</nav>
<body class="text-light" style="background: url('{% static 'Images/bgimg.jpg' %}') no-repeat center center;">

{% block content %}
<!-- Content Goes here -->
{% endblock content %}

<!-- Footer -->
<footer>

</footer>

</body>


<!-- To limit the ammount of characters that can be put int the forms. -->

<script>

id_name.oninput = function () {
    if (this.value.length > 50)
        this.value = this.value.slice(0,50); 
}

id_email.oninput = function () {
    if (this.value.length > 50)
        this.value = this.value.slice(0,50); 
}

id_number.oninput = function () {
    if (this.value.length > 12)
        this.value = this.value.slice(0,12); 
}

id_persons.oninput = function () {
    if (this.value.length > 2)
        this.value = this.value.slice(0,2); 
}

</script>
</html>

templates/bookings.html
{% extends "base.html" %}
  
{% block content %}

  <!-- display field -->
<h1 class="">Bookings already made.</h1>
 <div class="row" >

    <div class="col-sm-2">
    </div>

    <div class="col-sm-8">
      <div class="row" >
   {% for x in person %} 
   
    <div class="col-sm-4" id="booking_container">
      <h5> {{ x.name }} </h5>
      <h6> {{ x.email }} </h6>
      <h6> {{ x.phone }} </h6>
      <h6> {{ x.persons }} </h6>
      <h6> {{ x.date }} </h6>
      <h6>
          <a href = "/delete/{{ x.id }} " method="POST">
              <button>Delete</button>
          </a>
      </p>
    </div>
    
   {% endfor %} 
    </div>
  </div>

   <div class="col-sm-2">
   </div>


</div>
{% endblock %}

templates/dishmaker.html
{% extends "base.html" %}
  
{% block content %}

<form action="{% url 'make_dish' %}" method="post" enctype="multipart/form-data">
    
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/home.html
{% extends "base.html" %}
  
{% block content %}

<div class="row" >

    <div class="col-sm-2">
    </div>

    <div class="col-sm-8" id="center">
   

            <h1 class="text-center">Octi's Restaurant</h1>

    </div>

    <div class="col-sm-2">
    </div>

  </div>
{% endblock %}

templates/menu.html
{% extends "base.html" %}
  
{% block content %}


<h1 class="">Menu.</h1>
 <div class="row" >

    <div class="col-sm-2">
    </div>

    <div class="col-sm-8">
      <div class="row" >
   {% for dish in dish_list %} 
   
    <div class="col-sm-4" id="booking_container">

      <h5> {{ dish.name|safe }} </h5>
      <h5> {{ dish.text|safe }} </h5>
      <img class="img-fluid " src=" {{ dish.featured_image.url }}" alt="Tasty dish Image!">
      <form action="{% url 'delete_dish' dish.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Delete</button>
      </form>
    </div>
    
   {% endfor %} 
    </div>
  </div>

   <div class="col-sm-2">
   </div>


</div>
{% endblock %}

templates/reservation.html
{% extends "base.html" %}

{% block content %}


    <!-- imput field -->
<div class="container-fluid" id="bgimg">
    <div class="container mt-3" id="input">
        <h2 class="text-center text-light">Book a table!</h2>
        
        <form class="container mt-3" method="POST" action="reserv_table">
            {% csrf_token %}
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="id_name" placeholder="Enter email" name="reservation_name" maxlength="50">
                    <label for="id_name">Name</label>
                </div>
                <div class="form-floating mb-3 mt-3">
                    <input type="email" class="form-control" id="id_email" placeholder="Enter email" name="email_name" maxlength="50">
                    <label for="email">Email</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="number" class="form-control" id="id_number" placeholder="Phone number?" name="number_name" maxlength="12">
                    <label for="id_number">Phone number</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="number" class="form-control" id="id_persons" placeholder="How Many?" name="number_persons"maxlength="2">
                    <label for="id_persons">Number of People</label>
                </div>
                <div class="form-floating mt-3 mb-3">
                    <input type="datetime-local" class="form-control" id="id_date" placeholder="Date?" name="date_time">
                    <label for="id_date">Date</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
</div>
   


{% endblock %}